apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
    name: anfisa-test
spec:
  runPolicy: Serial
  source:
    type: Git
    git:
      uri: https://github.com/sveshnikov-artyom/anfisa
      ref: v.0.6.x-clean-code
  strategy:
    type: Docker
    dockerStrategy:
      noCache: false
      dockerfilePath: setup/Dockerfile
  output:
    to:
      kind: ImageStreamTag
      name: "anfisa-test:latest"
