apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
    name: anfisa-test
spec:
  runPolicy: Serial
  source:
    type: Git
    git:
      uri: https://github.com/ForomePlatform/anfisa
      ref: test
  strategy:
    type: Docker
    dockerStrategy:
      noCache: false
      dockerfilePath: setup/Dockerfile
  output:
    to:
      kind: ImageStreamTag
      name: "anfisa-test:latest"
