apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: druid-router
  labels:
    app: {{ include "druid.name" . }}
    chart: {{ include "druid.chart" . }}
    component: {{ .Values.router.name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}

spec:
  to:
    kind: Service
    name: druid-router
    weight: 100
  port:
    targetPort: http
  wildcardPolicy: None
