# Default values for mysql.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
hostNetwork: false
revisionHistoryLimit: 5

image:
  repository: mysql
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "8.0.26"

mysql:
#  rootPassword: dG9vcg==
#  Password: dG9vcg==
  rootPassword: dXNlcg==
  Password: dXNlcg==

#storage:
#  data:
#    claimName: internal-media-pvc
#    subPath: mysql

securityContext: {}

service:
  type: ClusterIP
  port: 3306


resources: {}
#  requests:
#    cpu: "1"
#    memory: "2048Mi"

env:
- 1env: MYSQL_ROOT_PASSWORD
  secretname: mysql-secret
  key: mysql-root-password
- 2env: MYSQL_USER
  value: user
- 3env: MYSQL_PASSWORD
  secretname: mysql-secret
  key: mysql-password
- 4env: MYSQL_DATABASE
  value: forome