apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: asset-foromeannotation-pvc-{{ .Values.annotator.project }}
  namespace: {{ .Values.annotator.project }}
  labels:
    app.kubernetes.io/component: {{ .Values.annotator.name }}
    app.kubernetes.io/instance: {{ .Values.annotator.name }}
    app.kubernetes.io/name: {{ .Values.annotator.name }}
    app: {{ .Values.annotator.name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  volumeMode: Filesystem
  storageClassName: ibmc-vpc-block-10iops-tier
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: asset-foromeannotationdata-pvc-{{ .Values.annotator.project }}
  namespace: {{ .Values.annotator.project }}
  labels:
    app.kubernetes.io/component: {{ .Values.annotator.name }}
    app.kubernetes.io/instance: {{ .Values.annotator.name }}
    app.kubernetes.io/name: {{ .Values.annotator.name }}
    app: {{ .Values.annotator.name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  volumeMode: Filesystem
  storageClassName: ibmc-vpc-block-10iops-tier
