apiVersion: v1
kind: Service
metadata:
  name: {{ include "druid.router.fullname" . }}
  labels:
    app: {{ include "druid.name" . }}
    chart: {{ include "druid.chart" . }}
    component: {{ .Values.router.name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.router.serviceType }}
  ports:
    - port: {{ .Values.router.servicePort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ include "druid.name" . }}
    release: {{ .Release.Name }}
    component: {{ .Values.router.name }}


#apiVersion: v1
#kind: Service
#metadata:
#  name: druid-router-test
#  labels:
#    app: druid
#    app.kubernetes.io/managed-by: Helm
#    chart: druid
#    component: router
#    heritage: Helm
#    release: druid
#
#  
#spec:
#  ports:
#    - name: http
#      protocol: TCP
#      port: 80
#      targetPort: http
#  selector:
#    app: druid
#    component: router
#    release: druid
#  type: ClusterIP
#  sessionAffinity: None
