dependencies:
- name: zookeeper
  version: 6.7.2
  repository: https://charts.bitnami.com/bitnami
  condition: zookeeper.enabled
- name: postgresql
  version: 10.4.0
  repository: https://charts.bitnami.com/bitnami
  condition: postgresql.enabled
- name: mongodb
  version: 10.13.0
  repository: https://charts.bitnami.com/bitnami
  condition: mongodb.enabled
