apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql
  namespace: test
  labels:
    app.kubernetes.io/instance: mysql
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: mysql

  annotations:
    meta.helm.sh/release-name: mysql
    meta.helm.sh/release-namespace: test
data:
  my.cnf: |-
    [mysqld]
    default_authentication_plugin=mysql_native_password
    skip-name-resolve
    explicit_defaults_for_timestamp
    port=3306
    max_allowed_packet=16M
    bind-address=0.0.0.0
    log-error=/opt/mysql/logs/mysqld.log
    character-set-server=UTF8
    collation-server=utf8_general_ci
    datadir=/opt/mysql/data

    [client]
    port=3306
    default-character-set=UTF8

    [manager]
    port=3306
